//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace id.volam.club.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCard_History
    {
        public long iid { get; set; }
        public string cAccName { get; set; }
        public string cCardCode { get; set; }
        public string cCardPin { get; set; }
        public short cCardType { get; set; }
        public short nStatus { get; set; }
        public System.DateTime dDateTime { get; set; }
        public string cIP { get; set; }
        public Nullable<bool> iValue { get; set; }
        public Nullable<bool> iFlag { get; set; }
        public string cDescription { get; set; }
    }
}
