//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace id.volam.club.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Habitus
    {
        public string cAccName { get; set; }
        public Nullable<int> iLeftSecond { get; set; }
        public System.DateTime dEndDate { get; set; }
        public Nullable<int> iUseSecond { get; set; }
    }
}
