//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace id.volam.club.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Info
    {
        public string cAccName { get; set; }
        public string cSecPassWord { get; set; }
        public string cPassWord { get; set; }
        public string cEmail { get; set; }
        public string cFullName { get; set; }
        public string cPhone { get; set; }
        public Nullable<long> iClientID { get; set; }
        public Nullable<System.DateTime> dLoginDate { get; set; }
        public Nullable<System.DateTime> dLogoutDate { get; set; }
        public short nExtPoint { get; set; }
        public short nExtPoint1 { get; set; }
        public short nExtPoint2 { get; set; }
        public short nExtPoint3 { get; set; }
        public short nExtPoint4 { get; set; }
        public short nExtPoint5 { get; set; }
        public short nExtPoint6 { get; set; }
        public short nExtPoint7 { get; set; }
        public Nullable<int> nUserIP { get; set; }
        public Nullable<int> nUserIPPort { get; set; }
        public Nullable<int> nFeeType { get; set; }
        public bool bParentalControl { get; set; }
        public bool bIsBanned { get; set; }
        public bool bIsUseOTP { get; set; }
        public byte iOTPSessionLifeTime { get; set; }
        public int iServiceFlag { get; set; }
    }
}
